---
# @author: Michele Dias Singaretti <midias@br.ibm.com>

- name: Report Status to Wsus
  block:
    - name: Run Update Session
      ansible.windows.win_shell: |
        $updateSession = new-object -com "Microsoft.Update.Session"
        $updates=$updateSession.CreateupdateSearcher().Search($criteria).Updates
      timeout: 300

    - name: Sleep for 10 seconds and continue with play
      delegate_to: localhost
      ansible.builtin.wait_for:
        timeout: 10

    - name: Run ResetAuthorization and DetectNow
      ansible.windows.win_shell: wuauclt.exe /ResetAuthorization /DetectNow
      become: true
      become_method: runas
      become_user: SYSTEM
      timeout: 300
      when: wsus_reset_authorization | bool

    - name: Run DetectNow and ReportNow
      ansible.windows.win_shell: wuauclt.exe {{ item }}
      args:
        executable: cmd.exe
      with_items:
        - /DetectNow
        - /ReportNow
        - /DetectNow
        - /ReportNow
        - /DetectNow
        - /ReportNow
        - /DetectNow
        - /ReportNow
        - /DetectNow
        - /ReportNow

  rescue:
    - name: Reporting status for wsus failed
      ansible.builtin.set_fact:
        error: '{{ ansible_failed_result }}'
