---
# @author: Rodrigo Chaves <rschaves@kyndryl.com>
# @name: Windows WSUS Report
# @base_version: 2.7.12
# @description: Windows Wsus complete report on Windows Servers
# @dependencies: Requires Sudo: () Yes (x) No
# @dependencies: Requires Ansible Pre-Reqs: (x) Yes () No

- name: Wsus Report
  hosts: "{{ affected_host }}"
  strategy: host_pinned
  ignore_unreachable: true

  tasks:
  - block:
    - name: Run PS script
      script: scripts/windows/wsus_report.ps1
      args:
        executable: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Unrestricted'
      register: wsusjson

    - name: Process win_shell output
      set_fact:
        wsus: "{{ wsusjson.stdout | from_json }}"
    - debug: var=wsus

    - name: Initialize ELK variables
      include_vars: roles/elastic_post_data/defaults/main.yml

    - name: Adding elastic_post_data role
      include_role:
        name: elastic_post_data
      vars:
        timestamp: "{{ lookup('pipe', 'date +\"%Y-%m-%dT%H:%M:%S.000Z\"') }}"
        customer_name: '{{ hostvars[inventory_hostname].client_name }}'
        country: '{{ elastic_country_code[hostvars[inventory_hostname].country | upper] }}'
        customer_code: "{{ hostvars[inventory_hostname].client_code }}"
        ciname: '{{ hostvars[inventory_hostname].inventory_hostname_short | lower }}'
        url: '{{ elastic_url }}'
        elastic_uri: "wsus_report-{{ lookup('pipe', 'date +\"%Y\"') }}/_update/{{ customer_code }}_{{ ciname }}_{{ lookup('pipe', 'date +\"%Y.%V\"') }}"
        elastic_doc: false
        elastic_data: |-
          {%- set doc = { "id": customer_code, "host_status": host_status } -%}
          {%- set i = doc.update({ "market": country if country in ["Brazil", "Mexico"] else "SSA" }) -%}
          {%- set i = doc.update({ "country": country }) -%}
          {%- set i = doc.update({ "created_at": timestamp }) -%}
          {%- set i = doc.update({ "hostname": ciname }) -%}
          {%- set i = doc.update({ "customer_name": customer_name }) -%}
          {%- set i = doc.update({ "wsusserver_name": wsus.wsus_info.Computername_WSUS }) -%}
          {%- set i = doc.update({ "wsusserver_version": wsus.wsus_info.Version }) -%}
          {%- set i = doc.update({ "wsusserver_port": wsus.wsus_info.Port }) -%}
          {%- set i = doc.update({ "wsusserver_protocol": wsus.wsus_info.ServerProtocolVersion }) -%}
          {%- set i = doc.update({ "stats_total": wsus.computer_stats.TotalComputers }) -%}
          {%- set i = doc.update({ "stats_stale": wsus.computer_stats.StaleComputers }) -%}
          {%- set i = doc.update({ "stats_need": wsus.computer_stats.NeedingUpdates }) -%}
          {%- set i = doc.update({ "stats_failed": wsus.computer_stats.FailedInstall }) -%}
          {%- set i = doc.update({ "stats_pending": wsus.computer_stats.PendingReboot }) -%}
          {%- set i = doc.update({ "endpoint_totalupdates": wsus.endpoint_stats.TotalUpdates }) -%}
          {%- set i = doc.update({ "endpoint_neededupdates": wsus.endpoint_stats.Needed }) -%}
          {%- set i = doc.update({ "endpoint_approvedupdates": wsus.endpoint_stats.Approved }) -%}
          {%- set i = doc.update({ "endpoint_declinedupdates": wsus.endpoint_stats.Declined }) -%}
          {%- set i = doc.update({ "endpoint_errorupdates": wsus.endpoint_stats.ClientInstallError }) -%}
          {%- set i = doc.update({ "wsusdrive_local": wsus.wsus_drive.LocalContentPath }) -%}
          {%- set i = doc.update({ "wsusdrive_total": wsus.wsus_drive.TotalSpaceGB }) -%}
          {%- set i = doc.update({ "wsusdrive_used": wsus.wsus_drive.UsedSpaceGB }) -%}
          {%- set i = doc.update({ "wsusdrive_free": wsus.wsus_drive.FreeSpaceGB }) -%}
          {%- set i = doc.update({ "wsusdrive_percent": wsus.wsus_drive.PercentFree }) -%}
          {%- set i = doc.update({ "endpointfailed_installation": wsus.endpointfailed_installation }) -%}
          {%- set i = doc.update({ "lastsync_starttime": wsus.lastsynchronizationinfo.StartTime }) -%}
          {%- set i = doc.update({ "lastsync_endtime": wsus.lastsynchronizationinfo.EndTime }) -%}
          {%- set i = doc.update({ "lastsync_error": wsus.lastsynchronizationinfo.Error }) -%}
          {%- set i = doc.update({ "last_wsuseventstime": wsus.last_wsusevents.TimeCreated }) -%}
          {%- set i = doc.update({ "last_wsuseventsid": wsus.last_wsusevents.Id }) -%}
          {%- set i = doc.update({ "last_wsuseventsleveldisplayname": wsus.last_wsusevents.LevelDisplayName }) -%}
          {%- set i = doc.update({ "last_wsuseventsmessage": wsus.last_wsusevents.Message }) -%}
          {%- set i = doc.update({ "osversions": wsus.OS_versions }) -%}
          {%- set i = doc.update({ "@timestamp": timestamp }) -%}
          {{ { "doc": doc, "doc_as_upsert": "true" } }}
