---
# @author: Rodrigo Chaves <rschaves@kyndryl.com>
# @name: Troubleshooting Windows Updates client
# @base_version: 2.7.11
# @description: Execute Windows Updates troubleshooting in servers
# @dependencies: WSUS Assignments
# @dependencies: Requires Sudo: (x) Yes () No
# @dependencies: Requires Ansible Pre-Reqs: (x) Yes () No

- name: Windows updates steps Troubleshooting
  gather_facts: false
  strategy: linear
  hosts: "{{ affected_host }}"
  roles: ['ansible_role_ssh_tunnel']
  ignore_unreachable: true

  tasks:
    - name: Run PS script
      script: 'scripts/windows/win_updates_troubleshooting.ps1'
      args:
        executable: 'powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Unrestricted'

    - name: Initiating update cycle
      win_shell: (New-Object -ComObject Microsoft.Update.AutoUpdate).DetectNow()

  rescue:
    - name: Troubleshooting task failed
      debug:
        msg: "Troubleshooting task failed"

    - name: Start troubleshooting
      include_tasks: ../roles/tasks/win_updates_troubleshooting.yml
      register: troubleshooting

    rescue:
    set_fact:
    error: "{{ ansible_failed_result }}"
