---
# @author: Rodrigo Chaves <rschaves@kyndryl.com>
# @copyright: (c) Kyndryl Inc. 2021. All Rights Reserved.
# @name: Run Windows Password Reset
# @base_version: 2.7.11
# @description: This playbook will reset windows password and update on vault
# @param: check_last:string:required:Check last password change date?: yes/no
# @dependencies: Vault Assignment
# @dependencies: Requires Sudo: (x) Yes () No
# @dependencies: Requires Ansible Pre-Reqs: (x) Yes () No

- name: Reset Windows Password
  hosts: '{{ affected_host }}'
  strategy: linear
  gather_facts: false

  tasks:
    - name: Include Windows password reset
      include_role:
        name: ansible_windows_password_reset
